### ISSUE TITLE
Error received while launching long running backtests

### ISSUE THREAD

**Issue by cnaccio** [QuantConnect/quantconnect-cli#6] opened 2020-11-29 02:20 UTC
I'm seeing the following when running long running backtest. Not a major issue, but just a heads up.

```
BG git:(main) ✗ ../scripts/push.sh && ../scripts/backtest.sh
 info Started looking for files to push
 info Successfully pushed 'BG/Main.cs'
 info Started compiling project 'BG'
 info Detected parameters: none
 info Build Request Successful for Project ID: 6165014, with CompileID: b4f4144ee4f2a001b4e82d392bd1ee5a-d5e3799c300314dd21801b23ddc3428d, Lean Version: 2.4.0.0.9880
 info Successfully compiled project 'BG'
 info Started backtest named 'Emotional Yellow-Green Fox' for project 'BG'
 info Backtest url: https://www.quantconnect.com/terminal/#open/6165014/66a30b70ac5a37463706c3720c3948a0
 error Cannot destructure property 'status' of 'err.response' as it is undefined.
```

**Comment by jmerle** [comment] 2020-11-29 19:02
I couldn't reproduce this issue, but I think it has to do with the way the CLI checks whether the backtest is done. At the moment it simply polls the API at a 250ms interval to see if the backtest is completed. Although I am not sure whether this caused your error (I could not reproduce it with a backtest taking 5 minutes), I have made some changes in https://github.com/QuantConnect/quantconnect-cli/commit/49ab6874d99b1807120b0fce92415099172bbf7d to make the polling mechanism more robust:
1. To prevent sporadic network errors from causing issues, failed requests are now retried up to 5 times.
2. To reduce the amount of requests being made (to hopefully reduce the chance of getting network errors and to prevent spamming the API needlessly) the interval between requests now varies. It starts at 250ms, but when the backtest takes longer and longer to complete the interval between requests moves up to 1,000ms, 2,000ms, 5,000ms and eventually 10,000ms.

These changes have been released in [1.4.2](https://github.com/QuantConnect/quantconnect-cli/releases/tag/v1.4.2). Can you upgrade and check whether the issue still occurs with this new polling mechanism?

**Comment by cnaccio** [comment] 2020-12-06 06:37
Hey @jmerle sorry for the delay; I actually don't think the issue is backtest specific, I think it's an issue with processing certain error responses. I just got the same error while trying to pull all files down. Let me play with it some more, and I'll post back with more specific details.

**Comment by jmerle** [comment] 2021-01-21 18:48
I am closing this issue due to inactivity. Please create a new one with more information if you're still facing this issue.

**Closed by jmerle** 2021-01-21 18:48 UTC
